<#
.SYNOPSIS
Downloads the prebuilt native dependencies (libgphoto2 and its dependencies) from https://github.com/momentobooth/native-deps.

.DESCRIPTION
Extracts the bundle to .native_deps/windows-x64 and writes .cargo/config.toml in the repository root, so that Cargo finds the libraries through the bundled pkgconf.
At build time, windows/CMakeLists.txt copies the runtime libraries next to the executable.

.PARAMETER ZipPath
Use a locally built bundle instead of downloading the pinned release, e.g. to test a new build. The checksum is not verified in that case.
#>
param(
  [string]$ZipPath
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$Release = 'libgphoto2-2.5.34-1'
$Asset = 'libgphoto2-windows-x64.zip'
$Sha256 = 'd5922224123c102a8703e7d0a6c937d5b41143747653f5953c4fb03a95c67e07'

$repositoryRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$destination = Join-Path $repositoryRoot '.native_deps\windows-x64'
$marker = Join-Path $destination '.source'
$source = if ($ZipPath) { (Resolve-Path $ZipPath).Path } else { "$Release/$Asset@$Sha256" }

if ((Test-Path $marker) -and (Get-Content $marker -Raw).Trim() -eq $source) {
  Write-Output "Native dependencies are up to date ($source)"
} else {
  $zip = $ZipPath
  if (-not $ZipPath) {
    $zip = Join-Path ([IO.Path]::GetTempPath()) $Asset
    Write-Output "Downloading $Release/$Asset"
    Invoke-WebRequest "https://github.com/momentobooth/native-deps/releases/download/$Release/$Asset" -OutFile $zip
    $actualSha256 = (Get-FileHash $zip -Algorithm SHA256).Hash
    if ($actualSha256 -ne $Sha256) {
      Remove-Item $zip
      throw "Checksum mismatch for $Asset, expected $Sha256 but got $actualSha256"
    }
  }

  if (Test-Path $destination) { Remove-Item $destination -Recurse -Force }
  Expand-Archive $zip $destination
  if (-not $ZipPath) { Remove-Item $zip }
  Set-Content $marker $source
  Write-Output "Extracted native dependencies to $destination"
}

# Cargo searches for configuration in the parent directories of the working directory, which includes this repository root for both cargo
# commands in rust/ and the Flutter build (build/windows/...).
$cargoConfig = Join-Path $repositoryRoot '.cargo\config.toml'
$generatedHeader = '# Generated by windows/get_native_deps.ps1, do not edit.'
if ((Test-Path $cargoConfig) -and -not (Get-Content $cargoConfig -First 1).Equals($generatedHeader)) {
  throw "$cargoConfig exists but was not generated by this script, refusing to overwrite it"
}
$bundle = $destination.Replace('\', '/')
New-Item -ItemType Directory -Force (Split-Path $cargoConfig) | Out-Null
Set-Content $cargoConfig @"
$generatedHeader
[env]
PKG_CONFIG = { value = '$bundle/tools/pkgconf.exe', force = true }
PKG_CONFIG_PATH = { value = '$bundle/lib/pkgconfig', force = true }
"@
