import 'dart:ui';

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'momento_booth_theme_data.freezed.dart';

@freezed
class MomentoBoothThemeData with _$MomentoBoothThemeData {

  const factory MomentoBoothThemeData({
    required Color defaultPageBackgroundColor,
    required Color primaryColor,
  }) = _MomentoBoothThemeData;

  factory MomentoBoothThemeData.defaults() => const MomentoBoothThemeData(
    defaultPageBackgroundColor: Color(0xFFFFFFFF),
    primaryColor: Color(0xFF00FF00), // Green
  );

}
