include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.generated.dart'
    - '**/*.json.dart'

linter:
  # More info: https://dart.dev/tools/linter-rules
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_bool_literals_in_conditional_expressions
    - avoid_dynamic_calls
    - avoid_field_initializers_in_const_classes 
    - avoid_private_typedef_functions
    - avoid_slow_async_io
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - combinators_ordering
    - directives_ordering
    # - discarded_futures # Enable ASAP
    - eol_at_end_of_file
    - join_return_with_assignment
    - missing_whitespace_between_adjacent_strings
    - noop_primitive_operations
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    # - prefer_expression_function_bodies # Yet to decide
    - prefer_null_aware_method_calls
    - sized_box_shrink_expand
    - unawaited_futures
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unreachable_from_main
    - use_enums
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_string_buffers
    - use_super_parameters
    - use_to_and_as_if_applicable
