targets:
  $default:
    builders:
      freezed:
        options:
          format: false
        generate_for:
          include:
            - lib/models/*.dart
            - lib/models/**/*.dart
            - lib/src/rust/models/*.dart
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/models/*.dart
            - lib/models/**/*.dart
      mobx_codegen:mobx_generator:
        generate_for:
          - lib/managers/*.dart
          - lib/models/subsystem.dart
          - lib/views/**/*_view_model.dart
      widgetbook_generator:use_case_builder:
        generate_for:
          - lib/views/**/*.dart
      widgetbook_generator:app_builder:
        generate_for:
          - lib/widgetbook.dart
      widgetbook_generator:addons_configs_builder:
        enabled: false
      widgetbook_generator:telemetry:
        enabled: false
      theme_tailor:
        options:
          theme_getter: on_theme_data
          theme_class_name: FluentTheme
          theme_data_class_name: FluentThemeData
        generate_for:
          - lib/views/photo_booth_screen/theme/photo_booth_theme.dart
