/**
 * This file is a configuration file generated by the `Template` extension on `vscode`
 * @see https://marketplace.visualstudio.com/items?itemName=yongwoo.template
 */
module.exports = {
  // You can change the template path to another path
  templateRootPath: "./.templates",
  // After copying the template file the `replaceFileTextFn` function is executed
  replaceFileTextFn: (fileText, templateName, utils) => {
    // @see https://www.npmjs.com/package/change-case
    const { changeCase } = utils;
    // You can change the text in the file
    return fileText
      .replace(
        /__templateNameToPascalCase__/g,
        changeCase.pascalCase(templateName)
      )
      .replace(
        /__templateNameToSnakeCase__/g,
        changeCase.snakeCase(templateName)
      );
  },
  renameFileFn: (fileName, templateName, utils) => {
    const { changeCase } = utils;
    const { path } = utils;
    const { base } = path.parse(fileName);
    return base.replace(/__templateNameToSnakeCase__/gm, changeCase.snakeCase(templateName));
  },
  renameSubDirectoriesFn: (directoryName, templateName, utils) => {
    const { changeCase } = utils;
    return directoryName.replace(/__templateNameToSnakeCase__/g, changeCase.snakeCase(templateName));
  }
};
