import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'open_source_package.freezed.dart';
part 'open_source_package.g.dart';

/// Generated by `just gen-licenses`, see tool/generate_licenses.dart.
const String openSourceLicensesAsset = 'assets/licenses/licenses.json.gz';

enum OpenSourceEcosystem { dart, rust, native, flutterEngine, toolchain }

enum OpenSourceUsage { runtime, buildTime }

/// A third-party package, library or tool that MomentoBooth uses, with its license.
@freezed
abstract class OpenSourcePackage with _$OpenSourcePackage {

  const factory OpenSourcePackage({
    required String name,
    required OpenSourceEcosystem ecosystem,

    /// Whether the package ends up in the application or is only used to build it.
    required OpenSourceUsage usage,

    /// Whether MomentoBooth depends on the package itself, rather than through another package.
    @Default(false) bool isDirect,
    String? version,
    String? description,
    String? url,

    /// The SPDX license expression, e.g. `MIT OR Apache-2.0`.
    String? license,

    /// The full license text.
    String? licenseText,
  }) = _OpenSourcePackage;

  factory OpenSourcePackage.fromJson(Map<String, Object?> json) => _$OpenSourcePackageFromJson(json);

  /// Loads all packages from [openSourceLicensesAsset]. Returns an empty list when the asset has not been generated.
  static Future<List<OpenSourcePackage>> loadAll() async {
    final ByteData data;
    try {
      data = await rootBundle.load(openSourceLicensesAsset);
    } on FlutterError {
      return const [];
    }
    final bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    return Isolate.run(() => decodeAll(bytes));
  }

  /// Decodes the gzipped JSON written by tool/generate_licenses.dart.
  @visibleForTesting
  static List<OpenSourcePackage> decodeAll(Uint8List bytes) {
    final json = jsonDecode(utf8.decode(gzip.decode(bytes))) as Map<String, dynamic>;
    // License texts are stored once and referenced by index, as many packages share the same text.
    final texts = (json['texts'] as List).cast<String>();
    return [
      for (final package in (json['packages'] as List).cast<Map<String, dynamic>>())
        OpenSourcePackage.fromJson({
          ...package,
          'licenseText': switch (package['licenseText']) {
            final int index => texts[index],
            _ => null,
          },
        }),
    ];
  }

}
