fastlane_require 'dotenv'

opt_out_usage

lane :ci_install_release_cert_using_api do
  api_key = app_store_connect_api_key(
    key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
    issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
    key_content: ENV['APP_STORE_CONNECT_KEY'],
    is_key_content_base64: true,
    in_house: false
  )

  setup_ci
  match(type: "developer_id")
end
